# Generated by Django 4.2.2 on 2023-07-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('decsciption', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
