# Generated by Django 4.2.2 on 2023-07-18 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('count', models.SmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=20)),
                ('led_panel', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=100)),
                ('video_card', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=10)),
                ('ram', models.CharField(max_length=200)),
                ('keyboard', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
