# Generated by Django 4.2.2 on 2023-07-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
