# Generated by Django 4.2.2 on 2023-07-18 04:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_alter_laptop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='title',
            field=ckeditor.fields.RichTextField(default=0, max_length=50),
        ),
    ]
